### ISSUE TITLE
"pop-support gtk" creates an unsized window on systems w/out tiling turned on

### ISSUE THREAD

**Issue by wagnerck** [pop-os/support-panel#3]
The newly launched Pop!OS support panel also includes a command-line verison named `pop-support`, and one of the options is `pop-support gtk`, which opens up the same widget that's now in the Settings app, only as its own window.

When you're using Pop!OS without tiling enabled (as I do), the widget window doesn't size correctly. It can be resized once opened but it's essentially the minimum size for an app. This is likely to be confusing for users and I don't think it's the intended behavior.

See the included screenshot:

![image](https://user-images.githubusercontent.com/96320715/156628080-fd32efd0-2620-4ff6-8513-9a012752fcfd.png)

**Comment by mmstick** [comment]
This is purely for testing purposes and not something users can find without poking around the terminal.

That said, I'll consider setting default window dimensions the next time I happen to be testing.

**Comment by wagnerck** [comment]
That's perfectly fair. Feel free to close this issue out if you want.
